### PR TITLE
removing print debug

### LINKED ISSUE #1: Wrong type for `entry_funcs`
Type of `entry_funcs` should be `entry_t` and not `input_t`

https://github.com/AuthenticExecution/TZ-Code-Generator/blob/598eca5caf177338c307c419f449736874792a27/tzcodegen/stubs/authentic_execution.c#L23

### LINKED ISSUE #2: Security: check index before access `entry_funcs` and `input_funcs`
We should check if the index `entry_id - 3` is a valid index (is within the bounds of the array). Same also applies `input_funcs`

https://github.com/AuthenticExecution/TZ-Code-Generator/blob/598eca5caf177338c307c419f449736874792a27/tzcodegen/stubs/authentic_execution.c#L686

Possible solution: define the size of both arrays using a `#define`. I would also define the starting index of entry points
```c
// somewhere at the beginning
#define NUM_INPUTS {num_inputs}
#define NUM_ENTRIES {num_entrys}
#define ENTRY_START_INDEX 3

// the arrays become as follows:
input_t input_funcs[NUM_INPUTS] = { {fill_inputs} };
entry_t entry_funcs[NUM_ENTRIES] = { {fill_entrys} };

// checks in handle_entry (for handle_input, it's analogous)
if(index - ENTRY_START_INDEX >= 0 && index - ENTRY_START_INDEX < NUM_ENTRIES) {
   // access the array
}
```

### LINKED ISSUE #4: Bad UUID string injected to `user_ta_header_defines.h`
I just tried the script for testing and I noticed a problem in the UUID  injected to `user_ta_header_defines.h`. This is the output:
```c
#define TA_UUID		{ 0xa0f7260d, 0x91d5, 0x4751, {0xa3, 0xeb, 0x 6, 0x03, 0xc3, 0x9b, 0x28, 0x4e} }
```

As you can see, there is one byte, namely `0x 6`, with a space between `0x` and `6`. Of course this would generate an error during compilation, so we should fix this issue.

I think the problem is in the following line:
https://github.com/AuthenticExecution/TZ-Code-Generator/blob/598eca5caf177338c307c419f449736874792a27/tzcodegen/generator.py#L34

I also attach the output of the script printed to the terminal:
```bash
(env) ubuntu@gianluca-private:~/authexec/TZ-Code-Generator$ TZ-Code-Gen -i example/whatever/ -o out
a0f7260d-91d5-4751-a3eb-0603c39b284e
213959748456308857955459706705327892558
a0f7260d-91d5-4751-a3eb-0603c39b284e

#define TA_UUID
        { 0xa0f7260d, 0x91d5, 0x4751, \ 

                { 0xa3, 0xeb, 0x 6, 0x03, 0xc3, 0x9b, 0x28, 0x4e} }
<class 'dict'> {}
{'entry1': 3}
Found outputs: ['button_pressed']
<class 'list'>
{'button_pressed': 16384}
```

### LINKED ISSUE #5: Remove debug prints
Debug prints should not be part of the public code :)

if you use `logging.debug(<string>)` that's fine, you can keep those instructions around without any problems. But any other debug instructions  (e.g., `print`) should be removed or replaced instead.

### PR DESCRIPTION
**Pull request by sepidehpouyan**
fix #1 
fix #2 
fix #4 
fix #5

### CODE REVIEW

File: tzcodegen/stubs/authentic_execution.c [hunk 1]
```diff
@@ -682,8 +648,11 @@ TEE_Result handle_entry(void *session, uint32_t param_types, TEE_Param params[4]
 
 	params[0].value.a = 0;
 	params[0].value.b = 0;
-	printf("Calling entry with ID %d\n", entry_id);
-    entry_funcs[entry_id - 3](session, param_types, params, data_input, size);
+	
+	if(entry_id - ENTRY_START_INDEX >= 0 && entry_id - ENTRY_START_INDEX < NUM_ENTRIES) {
+
+		entry_funcs[entry_id - 3](session, param_types, params, data_input, size);
```
Comment (gianlu33) [inline tzcodegen/stubs/authentic_execution.c:654]: you should use ENTRY_START_INDEX here as well

File: tzcodegen/stubs/authentic_execution.c [hunk 2]
```diff
@@ -637,31 +610,24 @@ TEE_Result handle_input(void *session, uint32_t param_types, TEE_Param params[4]
...
 
 	connection->nonce = connection->nonce + 1;
 	params[0].value.a = 0;
 	params[0].value.b = 0;
-	printf("Calling input with ID %d\n", connection->io_id);
-    input_funcs[connection->io_id](session, param_types, params, data, size);
 	
+	if(connection->io_id >= 0 && connection->io_id < NUM_INPUTS) {
+		input_funcs[connection->io_id](session, param_types, params, data, size);
+	}
```
Comment (gianlu33) [inline tzcodegen/stubs/authentic_execution.c:629]: maybe return an error in the `else`? Same in `handle_entry`

**Review by gianlu33 — APPROVED** [review]
This is good!
